/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { PoolAbi, PoolAbiInterface } from "../PoolAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "bool",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "enum AccessError",
      components: [
        {
          name: "CannotReinitialized",
          type: 0,
          typeArguments: null,
        },
        {
          name: "NotOwner",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "enum Error",
      components: [
        {
          name: "WrongAmount",
          type: 0,
          typeArguments: null,
        },
        {
          name: "ZeroIdentity",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Unauthorized",
          type: 0,
          typeArguments: null,
        },
        {
          name: "OnlySupportedAssets",
          type: 0,
          typeArguments: null,
        },
        {
          name: "AmountExceedsBalance",
          type: 0,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 10,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 11,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 6,
      type: "enum Option",
      components: [
        {
          name: "None",
          type: 0,
          typeArguments: null,
        },
        {
          name: "Some",
          type: 7,
          typeArguments: null,
        },
      ],
      typeParameters: [7],
    },
    {
      typeId: 7,
      type: "generic T",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 8,
      type: "str[12]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 9,
      type: "str[4]",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 10,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 11,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 12,
      type: "struct Deposit",
      components: [
        {
          name: "address",
          type: 5,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 18,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 13,
      type: "struct OwnershipRenounced",
      components: [
        {
          name: "previous_owner",
          type: 5,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 14,
      type: "struct OwnershipSet",
      components: [
        {
          name: "new_owner",
          type: 5,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 15,
      type: "struct OwnershipTransferred",
      components: [
        {
          name: "new_owner",
          type: 5,
          typeArguments: null,
        },
        {
          name: "previous_owner",
          type: 5,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 16,
      type: "struct Transfer",
      components: [
        {
          name: "from",
          type: 5,
          typeArguments: null,
        },
        {
          name: "to",
          type: 5,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 18,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 17,
      type: "struct Withdrawal",
      components: [
        {
          name: "address",
          type: 5,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 18,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 18,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: "account",
          type: 5,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
      ],
      name: "balance_of",
      output: {
        name: "",
        type: 18,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [],
      name: "deposit",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "exchange",
          type: 11,
          typeArguments: null,
        },
        {
          name: "asset_manager",
          type: 11,
          typeArguments: null,
        },
      ],
      name: "initialize",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "name",
      output: {
        name: "",
        type: 8,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [],
      name: "owner",
      output: {
        name: "",
        type: 6,
        typeArguments: [
          {
            name: "",
            type: 5,
            typeArguments: null,
          },
        ],
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [],
      name: "renounce_ownership",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "asset_manager",
          type: 11,
          typeArguments: null,
        },
      ],
      name: "set_asset_manager",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "symbol",
      output: {
        name: "",
        type: 9,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
      ],
      name: "total_supply",
      output: {
        name: "",
        type: 18,
        typeArguments: null,
      },
      attributes: null,
    },
    {
      inputs: [
        {
          name: "from",
          type: 5,
          typeArguments: null,
        },
        {
          name: "to",
          type: 5,
          typeArguments: null,
        },
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 18,
          typeArguments: null,
        },
      ],
      name: "transfer_from",
      output: {
        name: "",
        type: 2,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "new_owner",
          type: 5,
          typeArguments: null,
        },
      ],
      name: "transfer_ownership",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "asset",
          type: 11,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 18,
          typeArguments: null,
        },
      ],
      name: "withdraw",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [],
      name: "withdraw_all",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: 0,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 1,
      loggedType: {
        name: "",
        type: 12,
        typeArguments: [],
      },
    },
    {
      logId: 2,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 3,
      loggedType: {
        name: "",
        type: 14,
        typeArguments: [],
      },
    },
    {
      logId: 4,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 5,
      loggedType: {
        name: "",
        type: 13,
        typeArguments: [],
      },
    },
    {
      logId: 6,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 7,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 8,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 9,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 10,
      loggedType: {
        name: "",
        type: 16,
        typeArguments: [],
      },
    },
    {
      logId: 11,
      loggedType: {
        name: "",
        type: 3,
        typeArguments: [],
      },
    },
    {
      logId: 12,
      loggedType: {
        name: "",
        type: 15,
        typeArguments: [],
      },
    },
    {
      logId: 13,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 14,
      loggedType: {
        name: "",
        type: 4,
        typeArguments: [],
      },
    },
    {
      logId: 15,
      loggedType: {
        name: "",
        type: 17,
        typeArguments: [],
      },
    },
  ],
  messagesTypes: [],
  configurables: [],
};

export class PoolAbi__factory {
  static readonly abi = _abi;
  static createInterface(): PoolAbiInterface {
    return new Interface(_abi) as unknown as PoolAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): PoolAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as PoolAbi;
  }
}
