/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  TransferManager721UnsafeAbi,
  TransferManager721UnsafeAbiInterface,
} from "../TransferManager721UnsafeAbi";
const _abi = {
  types: [
    {
      typeId: 0,
      type: "()",
      components: [],
      typeParameters: null,
    },
    {
      typeId: 1,
      type: "b256",
      components: null,
      typeParameters: null,
    },
    {
      typeId: 2,
      type: "enum Identity",
      components: [
        {
          name: "Address",
          type: 3,
          typeArguments: null,
        },
        {
          name: "ContractId",
          type: 4,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 3,
      type: "struct Address",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 4,
      type: "struct ContractId",
      components: [
        {
          name: "value",
          type: 1,
          typeArguments: null,
        },
      ],
      typeParameters: null,
    },
    {
      typeId: 5,
      type: "u64",
      components: null,
      typeParameters: null,
    },
  ],
  functions: [
    {
      inputs: [],
      name: "get_exchange",
      output: {
        name: "",
        type: 4,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "exchange_contract",
          type: 4,
          typeArguments: null,
        },
      ],
      name: "initialize",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read", "write"],
        },
      ],
    },
    {
      inputs: [
        {
          name: "collection",
          type: 4,
          typeArguments: null,
        },
        {
          name: "from",
          type: 2,
          typeArguments: null,
        },
        {
          name: "to",
          type: 2,
          typeArguments: null,
        },
        {
          name: "token_id",
          type: 5,
          typeArguments: null,
        },
        {
          name: "amount",
          type: 5,
          typeArguments: null,
        },
      ],
      name: "transfer_nft",
      output: {
        name: "",
        type: 0,
        typeArguments: null,
      },
      attributes: [
        {
          name: "storage",
          arguments: ["read"],
        },
      ],
    },
  ],
  loggedTypes: [],
  messagesTypes: [],
  configurables: [],
};

export class TransferManager721UnsafeAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TransferManager721UnsafeAbiInterface {
    return new Interface(
      _abi
    ) as unknown as TransferManager721UnsafeAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): TransferManager721UnsafeAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as TransferManager721UnsafeAbi;
  }
}
