/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { TransferManager721Abi } from './TransferManager721Abi';

export { TransferManager721Abi__factory } from './factories/TransferManager721Abi__factory';
