/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  NftMarketplaceAbi,
  NftMarketplaceAbiInterface,
} from "../NftMarketplaceAbi";
const _abi = [
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [
      {
        type: "struct Address",
        name: "",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "fee_receiver",
    inputs: [],
    outputs: [
      {
        type: "enum Identity",
        name: "",
        components: [
          {
            type: "struct Address",
            name: "Address",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
          {
            type: "struct ContractId",
            name: "ContractId",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "pause",
    inputs: [],
    outputs: [
      {
        type: "bool",
        name: "",
      },
    ],
  },
  {
    type: "function",
    name: "supported_asset",
    inputs: [
      {
        type: "struct ContractId",
        name: "asset_id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
    ],
    outputs: [
      {
        type: "bool",
        name: "",
      },
    ],
  },
  {
    type: "function",
    name: "constructor",
    inputs: [
      {
        type: "struct Address",
        name: "admin",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "enum Identity",
        name: "receiver",
        components: [
          {
            type: "struct Address",
            name: "Address",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
          {
            type: "struct ContractId",
            name: "ContractId",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
        ],
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "list_nft",
    inputs: [
      {
        type: "struct ContractId",
        name: "contract_Id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "token_id",
      },
      {
        type: "struct ContractId",
        name: "asset_id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "price",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "delete_listing",
    inputs: [
      {
        type: "struct ContractId",
        name: "contract_Id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "token_id",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "update_price",
    inputs: [
      {
        type: "struct ContractId",
        name: "contract_Id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "token_id",
      },
      {
        type: "u64",
        name: "new_price",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "purchase_nft",
    inputs: [
      {
        type: "struct ContractId",
        name: "contract_Id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
      {
        type: "u64",
        name: "token_id",
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "set_admin",
    inputs: [
      {
        type: "struct Address",
        name: "admin",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "set_fee_receiver",
    inputs: [
      {
        type: "enum Identity",
        name: "receiver",
        components: [
          {
            type: "struct Address",
            name: "Address",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
          {
            type: "struct ContractId",
            name: "ContractId",
            components: [
              {
                type: "b256",
                name: "value",
              },
            ],
          },
        ],
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "set_pause",
    inputs: [],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
  {
    type: "function",
    name: "add_supported_asset",
    inputs: [
      {
        type: "struct ContractId",
        name: "asset_id",
        components: [
          {
            type: "b256",
            name: "value",
          },
        ],
      },
    ],
    outputs: [
      {
        type: "()",
        name: "",
        components: [],
      },
    ],
  },
];

export class NftMarketplaceAbi__factory {
  static readonly abi = _abi;
  static createInterface(): NftMarketplaceAbiInterface {
    return new Interface(_abi) as unknown as NftMarketplaceAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): NftMarketplaceAbi {
    return new Contract(
      id,
      _abi,
      walletOrProvider
    ) as unknown as NftMarketplaceAbi;
  }
}
