/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.88.1
  Forc version: 0.59.0
  Fuel-Core version: 0.26.0
*/

export type { RoyaltyManagerAbi } from './RoyaltyManagerAbi';

export { RoyaltyManagerAbi__factory } from './factories/RoyaltyManagerAbi__factory';
