/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RoyaltyManagerAbi } from "./RoyaltyManagerAbi";

export { RoyaltyManagerAbi__factory } from "./factories/RoyaltyManagerAbi__factory";
