/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.95.0
*/

export { Erc721V2Wl } from './Erc721V2Wl';
export { Erc721V2WlFactory } from './Erc721V2WlFactory';
