[project]
authors = ["Meliksah Gürtemel"]
entry = "main.sw"
license = "Apache-2.0"
name = "transfer_selector"

[dependencies]
interfaces = { path = "../interfaces" }
libraries = { path = "../libraries" }
