/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetManagerAbi } from "./AssetManagerAbi";

export { AssetManagerAbi__factory } from "./factories/AssetManagerAbi__factory";
