[project]
authors = ["Meliksah Gürtemel"]
entry = "main.sw"
license = "Apache-2.0"
name = "deposit_and_offer"

[dependencies]
interfaces = { path = "../../contracts-v1/interfaces" }
libraries = { path = "../../contracts-v1/libraries" }
