/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StrategyFixedPriceSaleAbi } from "./StrategyFixedPriceSaleAbi";

export { StrategyFixedPriceSaleAbi__factory } from "./factories/StrategyFixedPriceSaleAbi__factory";
