[project]
authors = ["Meliksah Gürtemel"]
entry = "main.sw"
license = "Apache-2.0"
name = "bulk_mint"

[dependencies]
src_3 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.1.2" }
src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.3" }
