[project]
authors = ["Meliksah Gürtemel"]
entry = "main.sw"
license = "Apache-2.0"
name = "strategy_fixed_price_sale"

[dependencies]
interfaces = { path = "../../interfaces" }
libraries = { path = "../../libraries" }
