/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TransferSelectorAbi } from "./TransferSelectorAbi";

export { TransferSelectorAbi__factory } from "./factories/TransferSelectorAbi__factory";
